# Vectors in Linear Algebra

A **Vector** is an ordered collection of numbers arranged in a single row or a single column. Unlike a scalar, a vector has both **magnitude** and **direction**.

Vectors are used to represent data, coordinates, features, and observations in mathematics, physics, and computer science. In Machine Learning, every data sample is commonly represented as a vector of features.

A **vector** is a collection of numerical values that represents both **magnitude** and **direction**.

#### Types of Vectors

##### Row Vector

```text
[2 4 6]

Shape:
(1, 3)

#### Column Vector
```text
[2]
[4]
[6]
Shape:
(3, 1)

#### Importing Library 

In [1]:
import numpy as np 

#### Creating a simple vector 

In [2]:
vector = np.array([2, 4, 6, 8])
print(vector)

[2 4 6 8]


#### Vector Properties

In [3]:
print("Vector :", vector)
print("Dimensions :", vector.ndim)
print("Shape :", vector.shape)
print("Size :", vector.size)
print("Data Type :", vector.dtype)

Vector : [2 4 6 8]
Dimensions : 1
Shape : (4,)
Size : 4
Data Type : int64


#### Creating a Row vector 

In [4]:
row_vector = np.array([[2, 4, 6]])
print(row_vector)
print("Shape :", row_vector.shape)

[[2 4 6]]
Shape : (1, 3)


#### Creating a Column vector

In [5]:
column_vector = np.array([[2],
                          [4],
                          [6]])
print(column_vector)
print("Shape :", column_vector.shape)

[[2]
 [4]
 [6]]
Shape : (3, 1)


#### Accessing Elements of a Vector

In [6]:
vector = np.array([10,20,30,40,50])
print(vector[0])
print(vector[2])
print(vector[-1])

10
30
50


#### Sclicing a Vector

In [7]:
vector = np.array([10,20,30,40,50,60])
print(vector[1:5])
print(vector[:3])
print(vector[3:])

[20 30 40 50]
[10 20 30]
[40 50 60]


#### Creating zero ones and random vectors 

In [8]:
zeros = np.zeros(5)
ones = np.ones(5)
random_vector = np.random.randint(1,10,5)
print("Zeros :", zeros)
print("Ones :", ones)
print("Random :", random_vector)

Zeros : [0. 0. 0. 0. 0.]
Ones : [1. 1. 1. 1. 1.]
Random : [2 1 7 3 3]
