# Matrices in Linear Algebra

A **Matrix** is a rectangular arrangement of numbers organized into **rows** and **columns**. It is one of the fundamental concepts in Linear Algebra and serves as the primary way to represent datasets, images, and mathematical transformations.

A matrix is a **two-dimensional array** of numbers arranged in rows and columns.

#### Import library 

In [1]:
import numpy as np

#### Creating a Matrix

In [2]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Matrix Properties 

In [3]:
print("Matrix:\n", matrix)
print("Dimensions:", matrix.ndim)
print("Shape:", matrix.shape)
print("Size:", matrix.size)
print("Data Type:", matrix.dtype)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: int64


#### Accessing Elements

In [4]:
print(matrix[0, 0])
print(matrix[1, 2])
print(matrix[2, 1])

1
6
8


#### Acessing rows 

In [5]:
print(matrix[0])
print(matrix[1])
print(matrix[2])

[1 2 3]
[4 5 6]
[7 8 9]


#### Accessing columns 

In [6]:
print(matrix[:, 0])
print(matrix[:, 1])
print(matrix[:, 2])

[1 4 7]
[2 5 8]
[3 6 9]


#### Matrix Sclicing 

In [7]:
print(matrix[:2, :2])
print(matrix[1:, 1:])

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


#### Zero Matrix 

In [8]:
zero_matrix = np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Ones Matrix 

In [9]:
ones_matrix = np.ones((3,3))
print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Identity Matrix

In [10]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Random Matrix

In [11]:
random_matrix = np.random.randint(1,10,(3,3))
print(random_matrix)

[[4 8 2]
 [9 2 6]
 [3 1 5]]
