#  Matrix Operations

Matrix operations are mathematical operations performed on matrices. They are fundamental to Linear Algebra and are widely used in Data Science, Machine Learning, Deep Learning, Computer Vision, and Artificial Intelligence.

The most commonly used matrix operations are:

- Matrix Addition
- Matrix Subtraction
- Scalar Multiplication
- Element-wise Multiplication
- Matrix Multiplication
- Matrix Transpose
- Matrix Sum
- Matrix Mean
- Matrix Maximum
- Matrix Minimum

#### Import Libraries 

In [1]:
import numpy as np

#### Creating two Matrices 

In [2]:
matrix1 = np.array([
    [1, 2],
    [3, 4]
])
matrix2 = np.array([
    [5, 6],
    [7, 8]
])
print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)

Matrix 1:
 [[1 2]
 [3 4]]

Matrix 2:
 [[5 6]
 [7 8]]


#### Matrix Addition 

In [3]:
addition = matrix1 + matrix2
print(addition)

[[ 6  8]
 [10 12]]


#### Matrix Subtraction 

In [4]:
subtraction = matrix2 - matrix1
print(subtraction)

[[4 4]
 [4 4]]


#### Scalar Multiplication 

In [5]:
scalar = 3
result = scalar * matrix1
print(result)

[[ 3  6]
 [ 9 12]]


#### Matrix Multiplication 

In [7]:
matrix_product = np.matmul(matrix1, matrix2)
print(matrix_product)

[[19 22]
 [43 50]]


#### Matrix Division 

In [8]:
division = matrix2 / matrix1
print(division)

[[5.         3.        ]
 [2.33333333 2.        ]]


#### Matrix Transpose 

In [9]:
transpose = matrix1.T
print(transpose)

[[1 3]
 [2 4]]


#### Matrix sum 

In [10]:
print(np.sum(matrix1))

10


#### Matrix mean 

In [11]:
print(np.mean(matrix1))

2.5


#### Matrix min and max 

In [12]:
print("Maximum :", np.max(matrix1))
print("Minimum :", np.min(matrix1))

Maximum : 4
Minimum : 1


#### Matrix shape 

In [13]:
print(matrix1.shape)

(2, 2)


#### Matrix dimension 

In [14]:
print(matrix1.ndim)

2


#### Matrix Size 

In [15]:
print(matrix1.size)

4
