# Transpose of a Matrix

The **transpose of a matrix** is a new matrix obtained by **interchanging its rows and columns**. In other words, every row of the original matrix becomes a column in the transposed matrix, and every column becomes a row.

The transpose of a matrix is represented by the symbol **Aᵀ** (read as "A transpose").

#### Import library 

In [2]:
import numpy as np

#### Creating a matrix using NumPy 

In [3]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(matrix)

[[1 2 3]
 [4 5 6]]


#### Find the transpose of the matrix

In [4]:
transpose = matrix.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


##### Checking shape of the matrix 

In [5]:
print("Original Shape :", matrix.shape)
print("Transpose Shape :", transpose.shape)

Original Shape : (2, 3)
Transpose Shape : (3, 2)


#### Using the `numpy.transpose()` function

In [6]:
transpose_matrix = np.transpose(matrix)
print(transpose_matrix)

[[1 4]
 [2 5]
 [3 6]]


#### Transpose of square matrix

In [7]:
square_matrix = np.array([
    [1, 2],
    [3, 4]
])
print("Original Matrix:\n", square_matrix)
print("\nTranspose:\n", square_matrix.T)

Original Matrix:
 [[1 2]
 [3 4]]

Transpose:
 [[1 3]
 [2 4]]


#### Transpose of a row vector 

In [8]:
row_vector = np.array([[10, 20, 30]])
print("Row Vector:\n", row_vector)
print("\nTranspose:\n", row_vector.T)

Row Vector:
 [[10 20 30]]

Transpose:
 [[10]
 [20]
 [30]]


#### Transpose of a column vector

In [9]:
column_vector = np.array([
    [10],
    [20],
    [30]
])
print("Column Vector:\n", column_vector)
print("\nTranspose:\n", column_vector.T)

Column Vector:
 [[10]
 [20]
 [30]]

Transpose:
 [[10 20 30]]
