#  Determinant of a Matrix

The **determinant** is a special numerical value that can be calculated from a **square matrix**. It provides important information about the matrix, such as whether the matrix is invertible, whether its rows or columns are linearly independent, and how the matrix transforms space.

The determinant is commonly denoted as:

```text
det(A)
or

|A|

#### Types of Determinant Values

##### Positive Determinant (> 0)

- Matrix is invertible.
- Orientation is preserved.

##### Negative Determinant (< 0)

- Matrix is invertible.
- Orientation is reversed (reflection).


##### Zero Determinant (= 0)

- Matrix is singular.
- Matrix cannot be inverted.
- Rows or columns are linearly dependent.

#### Import Library 

In [2]:
import numpy as np

#### Create a 2x2 Matrix

In [4]:
matrix = np.array([
    [4, 7],
    [2, 6]
])
print(matrix)

[[4 7]
 [2 6]]


#### Calculate the Determinant of a 2x2 Matrix

In [5]:
det = np.linalg.det(matrix)
print("Determinant:", det)

Determinant: 10.000000000000002


#### Determinant of a 3x3 Matrix

In [6]:
matrix = np.array([
    [1, 2, 3],
    [0, 4, 5],
    [1, 0, 6]
])
det = np.linalg.det(matrix)
print(det)

22.000000000000004


#### Singular Matrix (Determinant = 0)

In [7]:
matrix = np.array([
    [2, 4],
    [1, 2]
])
print(np.linalg.det(matrix))

0.0


#### Non-Singular Matrix (Determinant ≠ 0)

In [ ]:
matrix = np.array([
    [5, 2],
    [3, 4]
])
print(np.linalg.det(matrix))

#### Determinant of Identity Matrix

In [8]:
identity = np.eye(3)
print(identity)
print("Determinant:", np.linalg.det(identity))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinant: 1.0


#### determinant of a Diagonal Matrix

In [9]:
matrix = np.array([
    [3, 0, 0],
    [0, 5, 0],
    [0, 0, 2]
])
print(np.linalg.det(matrix))

30.000000000000004
