#  Inverse of a Matrix

The **inverse of a matrix** is another matrix that, when multiplied by the original matrix, produces the **Identity Matrix**.

The inverse of a matrix **A** is denoted by:

```text
A⁻¹

If

```text
A × A⁻¹ = I
```

where **I** is the Identity Matrix, then **A⁻¹** is called the inverse of **A**.

#### Importing Library 

In [1]:
import numpy as np 

#### Create a matrix using NumPy

In [2]:
matrix = np.array([
    [4, 7],
    [2, 6]
])
print(matrix)

[[4 7]
 [2 6]]


#### Find the determinant of the matrix

In [3]:
det = np.linalg.det(matrix)
print("Determinant:", det)

Determinant: 10.000000000000002


#### Calculate the Inverse of the matrix

In [4]:
inverse = np.linalg.inv(matrix)
print(inverse)

[[ 0.6 -0.7]
 [-0.2  0.4]]


#### Verify the result by multiplying the original matrix with its inverse to get the Identity Matrix.

In [5]:
identity = matrix @ inverse
print(identity)

[[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]


#### Inverse of 3x3 Matrix

In [6]:
matrix = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])
inverse = np.linalg.inv(matrix)
print(inverse)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
