# Rank of a Matrix

The **rank of a matrix** is the **maximum number of linearly independent rows or columns** in the matrix. It indicates how much unique information the matrix contains.

A matrix with a higher rank contains more independent information, while a lower-rank matrix contains redundant or dependent information.

#### Types of Matrix Rank

##### Full Rank Matrix

A matrix is **full rank** if its rank equals the smallest dimension.

Example:

```text
Shape = (3 × 3)

Rank = 3
```


#####  Rank Deficient Matrix

A matrix is **rank deficient** if its rank is less than the smallest dimension.

Example:

```text
Shape = (3 × 3)

Rank = 2

#### Import Library 

In [1]:
import numpy as np

#### Creating a matrix using NumPy

In [2]:
matrix = np.array([
    [1, 2],
    [3, 4]
])
print(matrix)

[[1 2]
 [3 4]]


#### Find the rank 

In [3]:
rank = np.linalg.matrix_rank(matrix)
print("Rank:", rank)

Rank: 2


#### Rank of a full rank matrix

In [4]:
matrix = np.array([
    [2, 1],
    [5, 3]
])
print(matrix)
print("\nRank:", np.linalg.matrix_rank(matrix))

[[2 1]
 [5 3]]

Rank: 2


#### Rank deficient matrix

In [5]:
matrix = np.array([
    [1, 2],
    [2, 4]
])
print(matrix)
print("\nRank:", np.linalg.matrix_rank(matrix))

[[1 2]
 [2 4]]

Rank: 1


#### Rank of a 3x3 matrix

In [6]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix)
print("\nRank:", np.linalg.matrix_rank(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank: 2


#### Identity matrix

In [7]:
identity = np.eye(4)
print(identity)
print("\nRank:", np.linalg.matrix_rank(identity))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Rank: 4


#### Zero Matrix 

In [8]:
zero_matrix = np.zeros((3,3))
print(zero_matrix)
print("\nRank:", np.linalg.matrix_rank(zero_matrix))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Rank: 0
