#  Identity Matrix

An **Identity Matrix** is a special type of **square matrix** in which:

- Every element on the **main diagonal** is **1**.
- Every other element is **0**.

The identity matrix is represented by the symbol:

```text
I
```

or

```text
Iₙ

where **n** is the size of the matrix.

The identity matrix plays the same role in matrix multiplication that the number **1** plays in ordinary multiplication.


#### Import library 

In [1]:
import numpy as np 

#### Create a 3x3 identity matrix

In [3]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Create a 5x5 identity matrix

In [4]:
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Identity Matrix Multiplication

In [5]:
A = np.array([
    [2,4],
    [6,8]
])
I = np.eye(2)
print("Matrix A")
print(A)
print("\nIdentity Matrix")
print(I)
print("\nA @ I")
print(A @ I)

Matrix A
[[2 4]
 [6 8]]

Identity Matrix
[[1. 0.]
 [0. 1.]]

A @ I
[[2. 4.]
 [6. 8.]]


#### determinant of a Identity Matrix

In [6]:
I = np.eye(4)
print(np.linalg.det(I))

1.0


#### Rank of a identity Matrix

In [7]:
I = np.eye(5)
print(np.linalg.matrix_rank(I))

5


#### Inverse of a Identity Matrix

In [8]:
I = np.eye(4)
print(np.linalg.inv(I))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
