# Singular Value Decomposition (SVD)

**Singular Value Decomposition (SVD)** is one of the most powerful matrix decomposition techniques in Linear Algebra. It decomposes any matrix into three simpler matrices, making it easier to analyze, compress, and process data.

Unlike Eigenvalue Decomposition, which only works directly with square matrices, **SVD works with any matrix**, whether it is square or rectangular.

#### Import Library 

In [1]:
import numpy as np 

#### Ceate a Matrix 

In [2]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(A)

[[1 2]
 [3 4]
 [5 6]]


#### COmpute SVD

In [3]:
U, S, VT = np.linalg.svd(A)

print("U Matrix:\n")
print(U)

print("\nSingular Values:\n")
print(S)

print("\nV Transpose:\n")
print(VT)

U Matrix:

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Singular Values:

[9.52551809 0.51430058]

V Transpose:

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


#### Shape of the matrix 

In [4]:
print("Shape of A :", A.shape)
print("Shape of U :", U.shape)
print("Shape of S :", S.shape)
print("Shape of VT:", VT.shape)

Shape of A : (3, 2)
Shape of U : (3, 3)
Shape of S : (2,)
Shape of VT: (2, 2)
