# Creating NumPy Arrays

### What is a NumPy Array?

A NumPy array is a collection of elements stored in a single object. Unlike Python lists, NumPy arrays are faster, more memory-efficient, and designed for mathematical computations.

NumPy arrays can have one or more dimensions.

### Importing the Numpy

In [1]:
import numpy as np 

### Creating an Array

The `np.array()` function is the most common way to create a NumPy array from a Python list.

In [ ]:
import numpy as np


arr = np.array([10, 20, 30, 40, 50])

print(arr)

print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


#### One-Dimensional Array

A one-dimensional array stores data in a single row. It is similar to a Python list but is optimized for numerical operations.

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### Two-Dimensional Array

A two-dimensional array stores data in rows and columns. It is commonly used to represent tables, spreadsheets, and datasets.

In [6]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)

print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


#### Three-Dimensional Array

A three-dimensional array contains multiple two-dimensional arrays. It is commonly used for image data, videos, and deep learning.

In [7]:
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print(arr)

print(type(arr))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


#### np.zeros()

Creates an array filled with zeros.

In [9]:
zeros = np.zeros((3,4))

print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### np.ones()

Creates an array filled with ones.

In [10]:
ones = np.ones((2,5))

print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### np.empty()

Creates an empty array. The values are uninitialized and may contain random memory values.

In [11]:
empty = np.empty((3,3))

print(empty)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### np.arange()

Creates an array with evenly spaced values within a specified range.

In [12]:
arr = np.linspace(0,100,11)

print(arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


#### Copying Arrays

Use the `copy()` method to create an independent copy of an array.

In [14]:
arr = np.array([1,2,3])

new_arr = arr.copy()

new_arr[0] = 100

print(arr)

print(new_arr)

[1 2 3]
[100   2   3]
