#  NumPy Array Properties

#### Creating Array

In [1]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr)

[[10 20 30]
 [40 50 60]]


#### shape

The `shape` property tells us the number of rows and columns in an array.

In [2]:
print(arr.shape)

(2, 3)


#### ndim

The `ndim` property returns the number of dimensions of an array.

In [3]:
print(arr.ndim)

2


#### size

The `size` property returns the total number of elements in the array.

In [4]:
print(arr.size)

6


#### dtype

The `dtype` property returns the data type of the array elements.

In [5]:
print(arr.dtype)

int64


#### astype()

The `astype()` method converts the data type of an array.

In [6]:
arr1 = np.array([1,2,3,4])

new_arr = arr1.astype(float)

print(new_arr)

print(new_arr.dtype)

[1. 2. 3. 4.]
float64


#### len()

The `len()` function returns the number of rows in the array.

In [7]:
print(len(arr))

2


In [9]:
marks = np.array([
    [85,90,78],
    [88,76,92],
    [95,89,84]
])

print("Student Marks")
print(marks)

print("\nShape      :", marks.shape)
print("Dimensions :", marks.ndim)
print("Size       :", marks.size)
print("Data Type  :", marks.dtype)

Student Marks
[[85 90 78]
 [88 76 92]
 [95 89 84]]

Shape      : (3, 3)
Dimensions : 2
Size       : 9
Data Type  : int64
