# NumPy Indexing and Slicing

#### Importing Numpy in python

In [2]:
import numpy as np

#### Creating one dimensional array

In [3]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


#### Positive Indexing

Positive indexing starts from **0** and moves from left to right.

In [4]:
print(arr[0])
print(arr[1])
print(arr[2])

10
20
30


#### Negative Indexing

Negative indexing starts from **-1** and moves from right to left.

In [5]:
print(arr[-1])
print(arr[-2])
print(arr[-3])

50
40
30


#### Slicing

Slicing extracts a range of elements.

Syntax:

array[start : stop]

In [7]:
print(arr[1:4])
print(arr[:3])

print(arr[2:])

print(arr[:])

print(arr[1:5])

[20 30 40]
[10 20 30]
[30 40 50]
[10 20 30 40 50]
[20 30 40 50]


#### Step Slicing

The third value in slicing specifies the step size.

Syntax:

array[start : stop : step]

In [8]:
print(arr[::2])

print(arr[1::2])

print(arr[::-1])

[10 30 50]
[20 40]
[50 40 30 20 10]


#### Creating a two-dimensional array

In [9]:
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


#### 2D Array Indexing

Use:

array[row, column]

In [10]:
print(matrix[0,0])

print(matrix[1,2])

print(matrix[2,1])

10
60
80


#### 2D Array Slicing

In [11]:
print(matrix[0:2,0:2])

print(matrix[:,1])

print(matrix[1,:])

print(matrix[:,0])

[[10 20]
 [40 50]]
[20 50 80]
[40 50 60]
[10 40 70]
