# NumPy Array Operations

#### Importing Numpy in python

In [1]:
import numpy as np 

#### Creating Array

In [2]:
arr1 = np.array([10, 20, 30, 40])

arr2 = np.array([1, 2, 3, 4])

print(arr1)
print(arr2)

[10 20 30 40]
[1 2 3 4]


#### Addition

The `+` operator adds corresponding elements from two arrays.

In [3]:
print(arr1 + arr2)

[11 22 33 44]


#### Subtraction

The `-` operator subtracts corresponding elements.

In [4]:
print(arr1 - arr2)

[ 9 18 27 36]


#### Multiplication

The `*` operator performs element-wise multiplication.

In [5]:
print(arr1 * arr2)

[ 10  40  90 160]


#### Division

The `/` operator divides corresponding elements.

In [6]:
print(arr1 / arr2)

[10. 10. 10. 10.]


#### Floor Division

The `//` operator returns the integer part of the division result.

In [7]:
print(arr1 // arr2)

[10 10 10 10]


#### Modulus

The `%` operator returns the remainder after division.

In [8]:
print(arr1 % arr2)

[0 0 0 0]


#### Power

The `**` operator raises each element to a given power.

In [9]:
print(arr2 ** 2)

[ 1  4  9 16]
