# Linear Algebra with NumPy

#### Importing Numpy in pyhton


In [1]:
import numpy as np 

#### Vector

A vector is a one-dimensional array that stores values in a single row or column.

In [2]:
vector = np.array([2, 4, 6])

print(vector)

[2 4 6]


#### Matrix

A matrix is a two-dimensional array consisting of rows and columns.

In [3]:
matrix = np.array([
    [1,2],
    [3,4]
])

print(matrix)

[[1 2]
 [3 4]]


#### Matrix Addition

Matrix addition adds the corresponding elements of two matrices having the same shape.

In [4]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A + B)

[[ 6  8]
 [10 12]]


#### Matrix Subtraction

Matrix subtraction subtracts the corresponding elements of two matrices having the same shape.

In [5]:
print(A - B)

[[-4 -4]
 [-4 -4]]


#### Matrix Multiplication

Matrix multiplication combines rows of the first matrix with columns of the second matrix.

In [6]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.matmul(A, B))

[[19 22]
 [43 50]]


#### Dot Product

The dot product multiplies corresponding elements of two vectors and then adds the results.

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))

32


#### Transpose

The transpose swaps the rows and columns of a matrix.

In [8]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


#### Determinant

The determinant is a single value that describes certain properties of a square matrix.

A determinant of **0** means the matrix cannot be inverted.

In [9]:
A = np.array([
    [2,3],
    [1,4]
])

print(np.linalg.det(A))

5.000000000000001


#### Inverse Matrix

The inverse of a matrix is used to solve systems of linear equations.

In [10]:
A = np.array([
    [2,1],
    [5,3]
])

print(np.linalg.inv(A))

[[ 3. -1.]
 [-5.  2.]]


#### Matrix Rank

The rank of a matrix represents the number of linearly independent rows or columns.

In [11]:
A = np.array([
    [1,2],
    [2,4]
])

print(np.linalg.matrix_rank(A))

1


#### Matrix Trace

The trace of a matrix is the sum of the main diagonal elements.

In [12]:
A = np.array([
    [2,3],
    [4,5]
])

print(np.trace(A))

7


#### Eigenvalues

Eigenvalues describe how a matrix stretches or shrinks vectors during a transformation.

In [13]:
A = np.array([
    [4,2],
    [1,3]
])

values, vectors = np.linalg.eig(A)

print(values)

[5. 2.]


#### Eigenvectors

Eigenvectors are special vectors whose direction remains unchanged after a matrix transformation.

In [14]:
print(vectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
