#  NumPy Random Module

#### Import Numpy in python 

In [3]:
import numpy as np

#### np.random.rand()

The `np.random.rand()` function generates random decimal numbers between **0 and 1**.

In [9]:
print(np.random.rand())
print(np.random.rand(5))
print(np.random.rand(3,3))

0.8516832448318585
[0.89683095 0.11856958 0.60682776 0.97694077 0.51647875]
[[0.95616925 0.79137558 0.35202235]
 [0.56591709 0.40807125 0.10228026]
 [0.45241567 0.21532097 0.46510271]]


#### np.random.randn()

The `np.random.randn()` function generates random numbers from a standard normal distribution with a mean of 0 and a standard deviation of 1.

In [10]:
print(np.random.randn())
print(np.random.randn(5))
print(np.random.randn(3,3))

0.38489917128561646
[-0.12247353 -0.23757587  0.03551758 -0.3351629  -0.52960418]
[[-1.64002668  0.0543449   0.54709662]
 [ 0.45590399  1.30365917  0.77540506]
 [-0.03527324 -1.20737258 -0.1160089 ]]


#### np.random.randint()

The `np.random.randint()` function generates random integers within a specified range.

In [12]:
print(np.random.randint(1,10))
print(np.random.randint(1,100,size=5))
print(np.random.randint(1,50,size=(3,4)))

3
[96 12 22 22 89]
[[ 3 13 34 39]
 [16 20 15 41]
 [13  5  1 15]]


#### np.random.choice()

The `np.random.choice()` function randomly selects elements from a list or array.

In [16]:
colors = ["Red","Blue","Green","Black"]

print(np.random.choice(colors))
print(np.random.choice(colors, size=3))

Black
['Green' 'Green' 'Red']


#### np.random.shuffle()

The `shuffle()` function randomly rearranges the elements of an existing array.

In [19]:
numbers = np.array([1,2,3,4,5,6])

np.random.shuffle(numbers)

print(numbers)

[3 1 6 4 5 2]
