# Boolean Indexing in NumPy

#### Boolean Indexing

Boolean Indexing filters an array using conditions.

If the condition is **True**, the value is selected.

If the condition is **False**, the value is ignored.

#### Importing Numpy in python

In [1]:
import numpy as np 

#### Creating Array

In [2]:
marks = np.array([45, 60, 78, 82, 95, 38, 67])

print(marks)

[45 60 78 82 95 38 67]


In [3]:
# Greater than 
print(marks[marks > 70])

[78 82 95]


In [4]:
#less than
print(marks[marks < 50])

[45 38]


In [5]:
#Greater than or equal to
print(marks[marks >= 50])

[60 78 82 95 67]


In [6]:
#less than or equal to 
print(marks[marks <= 60])

[45 60 38]


In [7]:
#Equal too
print(marks[marks == 82])

[82]


In [8]:
#Not equal to 
print(marks[marks != 60])

[45 78 82 95 38 67]


In [9]:
#And operator
print(marks[(marks >= 60) & (marks <= 90)])

[60 78 82 67]


In [10]:
#Not Operator
print(marks[~(marks > 70)])

[45 60 38 67]


In [11]:
#Filtering string
names = np.array(["Ali","Ahmed","Sara","Ayesha","Usman"])

print(names[names == "Sara"])

['Sara']


In [12]:
# 2D bolean indexing
marks = np.array([
    [85,90,78],
    [88,45,92],
    [35,89,84]
])

print(marks)
print(marks[marks > 80])

[[85 90 78]
 [88 45 92]
 [35 89 84]]
[85 90 88 92 89 84]
